### PR TITLE
Add VS Code config for the LSP

### PR DESCRIPTION
**Pull request by hra687261**

### CODE REVIEW

**Comment by Gbury** [comment]
Thanks, that's great ! I wonder if it would be possible/desirable to have a dedicated dolmen account/extension instead of you personally hosting and maintaining the vscode extension ?

**Comment by hra687261** [comment]
Fine by me! You'll have to create an Azure account and see the process on how to publish an extension, I can transfer the repo of the source code to you too.

**Comment by bclement-ocp** [comment]
It would be great to also publish the extension on https://open-vsx.org/ :)

**Comment by hra687261** [comment]
Done. Under my name in the mean time, until @Gbury creates a dolmen account.

**Comment by hra687261** [comment]
Fine by me as well.
I was thinking that in the future it could make sens to have a dolmen organisation on GitHub, for the source code of dolmen, this extension, and other tools that could be built on top of dolmen.

**Comment by Gbury** [comment]
Indeed, it could make sens to have an organization for dolmen at some point.

**Pull request merged**
